"""add foreign keys

Revision ID: 97eea1c37e56
Revises: a14816600976
Create Date: 2026-03-05 07:46:37.373445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97eea1c37e56'
down_revision: Union[str, Sequence[str], None] = 'a14816600976'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'platform_connections', 'creators', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'platform_connections', type_='foreignkey')
    # ### end Alembic commands ###
