"""initial schema

Revision ID: a14816600976
Revises: 
Create Date: 2026-03-05 07:37:34.385031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a14816600976'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creators',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('bio', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creators_email'), 'creators', ['email'], unique=True)
    op.create_index(op.f('ix_creators_username'), 'creators', ['username'], unique=True)
    op.create_table('platform_connections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('platform', sa.Enum('youtube', 'twitch', 'tiktok', name='platformtype'), nullable=False),
    sa.Column('platform_user_id', sa.String(), nullable=False),
    sa.Column('platform_username', sa.String(), nullable=False),
    sa.Column('platform_display_name', sa.String(), nullable=True),
    sa.Column('platform_thumbnail_url', sa.String(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_connections_creator_id'), 'platform_connections', ['creator_id'], unique=False)
    op.create_table('analytics_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('platform_connection_id', sa.String(), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=True),
    sa.Column('total_views', sa.Integer(), nullable=True),
    sa.Column('total_content', sa.Integer(), nullable=True),
    sa.Column('avg_engagement_rate', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['platform_connection_id'], ['platform_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_snapshots_platform_connection_id'), 'analytics_snapshots', ['platform_connection_id'], unique=False)
    op.create_table('content_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('platform_connection_id', sa.String(), nullable=False),
    sa.Column('platform_content_id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('content_type', sa.Enum('video', 'short', 'stream', 'clip', name='contenttype'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.ForeignKeyConstraint(['platform_connection_id'], ['platform_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_items_creator_id'), 'content_items', ['creator_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('milestone', 'spike', 'new_content', 'sync_complete', 'platform_connected', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('extra_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_creator_id'), 'notifications', ['creator_id'], unique=False)
    op.create_table('content_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('content_item_id', sa.String(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('like_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('share_count', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['content_item_id'], ['content_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_snapshots_content_item_id'), 'content_snapshots', ['content_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_snapshots_content_item_id'), table_name='content_snapshots')
    op.drop_table('content_snapshots')
    op.drop_index(op.f('ix_notifications_creator_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_content_items_creator_id'), table_name='content_items')
    op.drop_table('content_items')
    op.drop_index(op.f('ix_analytics_snapshots_platform_connection_id'), table_name='analytics_snapshots')
    op.drop_table('analytics_snapshots')
    op.drop_index(op.f('ix_platform_connections_creator_id'), table_name='platform_connections')
    op.drop_table('platform_connections')
    op.drop_index(op.f('ix_creators_username'), table_name='creators')
    op.drop_index(op.f('ix_creators_email'), table_name='creators')
    op.drop_table('creators')
    # ### end Alembic commands ###
